version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./SecretFriendOrganizerApi/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
      - keycloak
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=secret_friend_db;User Id=postgres;Password=admin123;
      - Keycloak__Authority=http://localhost:8080/realms/SecretFriend/.well-known/openid-configuration
      - Keycloak__ClientId=secret-friend-client
      - Keycloak__ClientSecret=JU1WGNWXNhRqZqn9FQPskWlWGRRMicAI

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: admin123
      KC_DB_URL_HOST: db
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /infra/keycloak/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./keycloak-config:/infra/keycloak

volumes:
  postgres_data:
